### ISSUE TITLE
ESP8266 modules, RX, TX, ground, and 3v

### ISSUE THREAD

**Issue by mjschipper** [mhgolkar/Melon_Green#1]
Hi. What a fantastic project!

I've ordered some PCBs to be made and i am interested in trying to use an ESP8266 wifi module to convert the serial interface to wifi using esp-link (https://github.com/jeelabs/esp-link).

I've been scanning over the schematics to try and find a 3v VCC to complete the serial pinout to ESP8266 connection. Is there one in the design?

P.S if you have any photos of your setup of pumps, etc i'd be really interested in seeing them.

**Comment by mjschipper** [comment]
Looks like this breakout board converts it to 5v https://www.aliexpress.com/item/4000814189272.html

Have you tried a similar wifi or logging system?

**Comment by mhgolkar** [comment]
Hi @mjschipper 

The short answer considering "a 3v VCC to complete the serial pinout to ESP8266 connection", (as far as I recall) is no.
There is not a clean / existent way to get it from the board readily.

Melon-Green board can be seen as an `Arduino Uno` plus some relays connected to it (with optocoupler protection;)
So experimentally speaking, anything that works with Uno properly, could connect to your board and get the job done.

One doesn't even need to order PCBs to be made if the project does not require to be mounted on a single board.
We may use an Arduino Uno with a relay shield instead and most-likely [re-configuring pins](https://github.com/mhgolkar/Melon_Green/blob/05d1ea48ee355ca7ab1622785f85d983cf5c477c/Melon_Green/modules/Presets.v1.h) to have them up and running. In that case, an expansion board may come in handy to have 3v VCC and keep things tidy as well.

And yes, you may try adapters on Melon-Green as well. Yet be aware. Because not every module plays nicely with the current flow, you may experience weird glitches such as inaccurate sensory data (analog ones specially,) restart chains (due to current deficit for the main IC,) overheating, etc. Calibration may solve some of these issues, but there is no guarantee. You need to experiment.

I didn't try logging. Yet it sounds a very good idea with a lot of benefits.
The source code (~ essential functions) may need some tweaks to print more information, such as read sensory data, switching time-stamps, etc. In that case, I hope already crammed physical memory of the IC can handle it. That might be a challenge.

If you made it work, consider sharing your experience and the code.
I appreciate it.

My main setups of melon-green was for (hobby-) terrariums here and there. I didn't document them unfortunately and they are not around any more. They where basic setups with domestic utilities (LEDs, ceramic heaters, solenoid valves, plastic pipes for irrigation, etc.) so ugly, and relatively large.
Plants seemed to be happy with them anyway.
I used to connect my android tablet with a usb-serial adapter to the board once in a while for configuration and test if the utilities work as expected.
The overall setup is the same for smaller or larger scales.
I once contemplated having multiple boards connected to a central mind (raspberry-pi) and have multiple climates and a dashboard. But it didn't go any further. I think it's technically possible and may help with conducting botanic experiments.
Anyway! The point I guess is worth mentioning here (for the record,) is that: if one is going to use more powerful pumps, heaters, etc. (let's say industrial level or ones which may apply unexpected heat to the main board,) a good idea is to use contactors (maybe on a rail, after relays) for extra protection and most-likely to have the current needed. Though I think for setups that large (where level of reliability may also be of financial concern) our Melon-Green may not be battle tested enough so the right choice.

I hope it's useful.
Have a good experience
